package info.loenwind.owlgen;

import java.util.List;

public interface IGenome {

  /**
   * Returns an String that contains a binary representation of the genome. That
   * String may not be printable.
   */
  String getData();

  /**
   * Sets the complete genome from the given String. The String must have been
   * generated by a genome with the same, or a shorter, gene set.
   * <p>
   * Strings with invalid data are silently ignored.
   */
  void setData(String data);

  /**
   * Starts syncing data using the datawatcher.
   * <p>
   * Call this after creating the object.
   */
  void startSync();

  /**
   * Returns the parent0 gene set.
   * <p>
   * The returned list can be manipulated until startSync() has been called.
   */
  List<IGene> getGenes0();

  /**
   * Returns the parent1 gene set.
   * <p>
   * The returned list can be manipulated until startSync() has been called.
   */
  List<IGene> getGenes1();

  /**
   * Returns the expressed gene set.
   * <p>
   * The returned list can be manipulated until startSync() has been called.
   */
  List<IGene> getGenesE();

}